# Generated by Django 6.0.6 on 2026-06-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('short', models.CharField(help_text='Short name e.g. CNA, CMA', max_length=20)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon', models.CharField(default='🏥', help_text='Emoji icon', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('category', models.CharField(choices=[('nursing', 'Nursing'), ('allied_health', 'Allied Health'), ('life_support', 'Life Support')], default='nursing', max_length=20)),
                ('duration', models.CharField(help_text='e.g. 2–4 Weeks', max_length=50)),
                ('hours', models.CharField(help_text='e.g. 77 Clock Hours', max_length=50)),
                ('description', models.TextField()),
                ('schedules', models.TextField(help_text='One schedule per line e.g. Weekday Classes')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'ordering': ['order', 'title'],
            },
        ),
    ]
