# Generated by Django 6.0.6 on 2026-06-17 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_event'),
        ('lms', '0014_alter_lesson_options_alter_module_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Link to LMS course for enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='lms.course'),
        ),
    ]
