# Generated by Django 6.0.6 on 2026-06-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_program_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('program', models.CharField(blank=True, help_text='e.g. CNA, CMA', max_length=20)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('ssn_card', 'Social Security Card'), ('diploma', 'High School Diploma / GED'), ('immunization', 'Immunization Records'), ('tb_test', 'TB Test Results'), ('background_check', 'Background Check'), ('other', 'Other Document')], max_length=30)),
                ('file', models.FileField(upload_to='applicant_documents/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
            ],
            options={
                'verbose_name': 'Application Document',
                'verbose_name_plural': 'Application Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
