# Generated by Django 6.0.6 on 2026-07-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Online/Hybrid program with LMS access'),
        ),
    ]
