# Generated by Django 6.0.6 on 2026-07-28 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_program_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('days', models.CharField(help_text='e.g. Mon-Fri, Mon/Wed/Fri', max_length=100)),
                ('seats_total', models.IntegerField(default=15)),
                ('seats_filled', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_list', to='core.program')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
