# Generated by Django 6.0.6 on 2026-07-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_classschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Program price (overrides course price)', max_digits=8, null=True),
        ),
    ]
