# Generated by Django 6.0.6 on 2026-08-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_program_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='applications/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
