# Generated by Django 6.0.6 on 2026-06-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentitem',
            name='content_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('ppt', 'PowerPoint Presentation'), ('word', 'Word Document'), ('youtube', 'YouTube Embedded Video'), ('video', 'Direct Video File'), ('text', 'Text / Rich Content')], max_length=20),
        ),
    ]
