# Generated by Django 6.0.6 on 2026-06-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Minutes. 0 = no limit.'),
        ),
    ]
