# Generated by Django 6.0.6 on 2026-06-12 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_studentstreak_coursereview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('element_type', models.CharField(choices=[('flashcards', 'Flashcard Deck'), ('knowledge_check', 'Quick Knowledge Check'), ('scenario', 'Clinical Scenario'), ('drag_drop', 'Drag & Drop Labeling')], max_length=20)),
                ('order', models.IntegerField(default=1)),
                ('data', models.JSONField(default=dict)),
                ('points', models.IntegerField(default=10)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_elements', to='lms.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='InteractiveCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_completions', to=settings.AUTH_USER_MODEL)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.interactiveelement')),
            ],
            options={
                'unique_together': {('student', 'element')},
            },
        ),
    ]
