# Generated by Django 6.0.6 on 2026-06-12 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_interactiveelement_interactivecompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiveelement',
            name='attached_to',
            field=models.ForeignKey(blank=True, help_text='Show as a popup after this content item is completed. Leave blank to show at end of lesson.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactive_triggers', to='lms.contentitem'),
        ),
    ]
