# Generated by Django 6.0.6 on 2026-06-15 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_question_image_question_match_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
    ]
