# Generated by Django 6.0.6 on 2026-07-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_alter_lesson_options_alter_module_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_email', models.EmailField(db_index=True, max_length=254)),
                ('stage', models.CharField(choices=[('form_started', 'Form Started'), ('form_submitted', 'Form Submitted'), ('payment_page', 'Visited Payment Page'), ('payment_completed', 'Payment Completed'), ('course_started', 'Course Started')], max_length=30)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('student_email', 'stage')},
            },
        ),
    ]
