# Generated by Django 6.0.6 on 2026-07-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_studentjourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
