# Generated by Django 6.0.6 on 2026-07-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_subscription_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='receipt_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
