# Generated by Django 6.0.6 on 2026-07-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_subscription_receipt_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_final_exam',
            field=models.BooleanField(default=False),
        ),
    ]
