# Generated by Django 6.0.6 on 2026-08-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_quiz_is_final_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='access_blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_plan',
            field=models.CharField(default='full', max_length=20),
        ),
    ]
