# Generated by Django 6.0.6 on 2026-08-06 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0020_lessontimelog'),
    ]

    operations = [
    ]
