# Generated by Django 6.0.6 on 2026-08-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0021_fake_required_hours'),
    ]

    operations = [
    ]
