# Generated by Django 6.0.6 on 2026-08-06 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0022_fake_required_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='required_hours',
            field=models.PositiveIntegerField(default=0, help_text='Minimum hours required to unlock final exam'),
        ),
    ]
